language: node_js
node_js:
  - "0.12"
  - "4"
  - "5"
  - "6"
install:
  - npm install
script:
  - mkdir newdir && cd newdir && node ../cli/index.js genConfig && node ../cli/index.js reference && node ../cli/index.js test
