addons: # get google-chrome [stable|beta]
  chrome: beta
language: node_js
node_js:
  - "8.1"
install:
  - npm install
script:
  - npm run unit-test

# vvv can remove the following lines after sharp package dependency is removed vvv
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
