
image: ubuntu:22.04

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get update
  - apt-get install curl wget -y
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - apt-get install ./google-chrome-stable_current_amd64.deb  -y
  - curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
  - . ~/.nvm/nvm.sh
  - nvm --version
  - nvm install $NODEJS
  - npm install -g npm
  - node -v
  - npm -v
  - npm install

tests:
  script:
    - npm run lint && npm run unit-test
    - npm run sanity-test
    - npm run smoke-test
  artifacts:
    when: always
    paths:
      - test/configs/backstop_data
    expire_in: 1 month
  parallel:
    matrix:
      - NODEJS:
          - 14
          - 16
