name: "Install and Cache Playwright"
description: "Sets up a cache and/or installs Playwright and its binaries."

inputs:
  WORKSPACE_ROOT:
    description: "The workspace root."
    required: true

runs:
  using: "composite"
  steps:
    - name: Get installed Playwright version
      shell: bash
      working-directory: ${{ inputs.WORKSPACE_ROOT }}
      id: playwright-version
      run: echo "PLAYWRIGHT_VERSION=$(cat package.json | jq -r '.dependencies.playwright' || 'latest')" >> $GITHUB_ENV

    - name: Cache playwright binaries
      uses: actions/cache@v3
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

    - shell: bash
      working-directory: ${{ inputs.WORKSPACE_ROOT }}
      run: npm ci

    - shell: bash
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      working-directory: ${{ inputs.WORKSPACE_ROOT }}
      run: npx playwright install --with-deps

    - shell: bash
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      working-directory: ${{ inputs.WORKSPACE_ROOT }}
      run: npx playwright install-deps
