name: Build Compare Test

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write
  pull-requests: write

env:
  NODE_VERSION: 20

jobs:
  build-compare:
    name: 🚜 Build Compare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: ⬢ Setup Node & Cache
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: ↧ Install
        run: npm ci

      - name: "Run `npm run build-compare`"
        run: |
          npm run build-compare
