name: Docker Smoke Test Checks

on:
  workflow_dispatch:
  workflow_call:

permissions:
  actions: write
  checks: write
  contents: write
  pull-requests: write
  packages: write

env:
  BRANCH_NAME: ${{ github.event.pull_request.head_ref || github.event.pull_request.head.ref_name || github.head_ref || github.ref_name }}
  NODE_VERSION: 20
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  smoke-test-puppeteer:
    name: 💨 Puppeteer
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout actions
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.head_ref || github.ref_name || github.ref }}
          sparse-checkout: |
            .github/actions
          path: actions

      - uses: ./actions/.github/actions/setup-base
        id: base

      - uses: ./actions/.github/actions/prepare-docker
        with:
          REGISTRY: ${{ env.REGISTRY }}
          ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "𓋏 Run `backstop test --confg=backstop_features` in Docker"
        continue-on-error: true
        run: |
          set +e
          cd test/configs/ && docker run --rm -t --mount type=bind,source="$(pwd)",target=/src $REGISTRY/$IMAGE_NAME_LC:$TAG test --config=backstop_features

      - name: "Validate Puppeteer Docker Test Results"
        uses: ./actions/.github/actions/smoke-test-checks
        with:
          WORKSPACE_ROOT: ${{ steps.base.outputs.WORKSPACE_ROOT }}
          RUNNER: "Puppeteer"
          FIXTURE: "smoke-test-docker.json"

  smoke-test-playwright:
    name: 💨 Playwright
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout actions
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.head_ref || github.ref_name || github.ref }}
          sparse-checkout: |
            .github/actions
          path: actions

      - uses: ./actions/.github/actions/setup-base
        id: base

      - uses: ./actions/.github/actions/prepare-docker
        with:
          REGISTRY: ${{ env.REGISTRY }}
          ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "🎭 Run `backstop test --confg=backstop_features_pw` in Docker"
        continue-on-error: true
        run: |
          set +e
          cd test/configs/ && docker run --rm -t --mount type=bind,source="$(pwd)",target=/src $REGISTRY/$IMAGE_NAME_LC:$TAG test --config=backstop_features_pw

      - name: "Validate Playwright Docker Test Results"
        uses: ./actions/.github/actions/smoke-test-checks
        with:
          WORKSPACE_ROOT: ${{ steps.base.outputs.WORKSPACE_ROOT }}
          RUNNER: "Playwright"
          FIXTURE: "smoke-test-playwright-docker.json"
